version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "S3cretPa55word123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  evidence-knih:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports: 
      - "8080:80"
    